const situationType = [
    {
        id: 1,
        name: "Sanctions",
        icon: "",
    },
    {
        id: 2,
        name: "Offense",
        icon: "",
    },
    {
        id: 3,
        name: "Defense",
        icon: "",
    },
];

const actionType = [
    {
        id: 1,
        name: "Success",
        icon: "",
    },
    {
        id: 2,
        name: "Failure",
        icon: "",
    },
    {
        id: 3,
        name: "Block",
        icon: "",
    },
];

const playerActions = [
    {
        id: 1,
        name: "Yellow Card",
        situation: 1,
        icon: "",
        type: 2,
    },
    {
        id: 2,
        name: "Red Card",
        situation: 1,
        icon: "",
        type: 2,
    },
    {
        id: 3,
        name: "Blue Card",
        situation: 1,
        icon: "",
        type: 2,
    },
    {
        id: 4,
        name: "2 Minutes",
        situation: 1,
        icon: "",
        type: 2,
    },
    {
        id: 5,
        name: "Travelling",
        situation: 2,
        icon: "",
        type: 2,
    },
    {
        id: 6,
        name: "Carrying",
        situation: 2,
        icon: "",
        type: 2,
    },
    {
        id: 7,
        name: "Offensive Foul",
        situation: 2,
        icon: "",
        type: 2,
    },
    {
        id: 8,
        name: "Lost Ball",
        situation: 2,
        icon: "",
        type: 2,
    },
    {
        id: 9,
        name: "Foul",
        situation: 2,
        icon: "",
        type: 3,
    },
    {
        id: 10,
        name: "Block",
        situation: 2,
        icon: "",
        type: 3,
    },
    {
        id: 11,
        name: "2 Minutes forced",
        situation: 2,
        icon: "",
        type: 1,
    },
    {
        id: 12,
        name: "7m forced",
        situation: 2,
        icon: "",
        type: 1,
    },
    {
        id: 13,
        name: "One on One Win",
        situation: 2,
        icon: "",
        type: 1,
    },
    {
        id: 14,
        name: "7m",
        situation: 3,
        icon: "",
        type: 2,
    },
    {
        id: 15,
        name: "One on One Lost",
        situation: 3,
        icon: "",
        type: 2,
    },
    {
        id: 16,
        name: "Foul",
        situation: 3,
        icon: "",
        type: 3,
    },
    {
        id: 17,
        name: "Block",
        situation: 3,
        icon: "",
        type: 3,
    },
    {
        id: 18,
        name: "Offensive Foul",
        situation: 3,
        icon: "",
        type: 1,
    },
    {
        id: 19,
        name: "Steal",
        situation: 3,
        icon: "",
        type: 1,
    },
];

const playersList = [
    {
        id: 1,
        name: "Afonso SimÃµes",
        pos: "PD",
        number: 36,
    },
    {
        id: 2,
        name: "Alexandre Silva",
        pos: "PV",
        number: 49,
    },
    {
        id: 3,
        name: "Christian Rato",
        pos: "LE",
        number: 2,
    },
    {
        id: 4,
        name: "Diogo Antunes",
        pos: "PV",
        number: 83,
    },
    {
        id: 5,
        name: "Goncalo Cardoso",
        pos: "PD",
        number: 88,
    },
    {
        id: 6,
        name: "JoÃ£o PorfÃ­rio",
        pos: "PE",
        number: 6,
    },
    {
        id: 7,
        name: "Leonardo GraÃ§a",
        pos: "PV",
        number: 7,
    },
    {
        id: 8,
        name: "LuÃ­s Freitas",
        pos: "LD",
        number: 20,
    },
    {
        id: 9,
        name: "Miguel SilvÃ©rio",
        pos: "C",
        number: 5,
    },
    {
        id: 10,
        name: "Pedro Pires",
        pos: "C",
        number: 11,
    },
    {
        id: 11,
        name: "Rodrigo Rocha",
        pos: "LE",
        number: 18,
    },
    {
        id: 12,
        name: "Tiago Sousa",
        pos: "PD",
        number: 4,
    },
    {
        id: 13,
        name: "TomÃ¡s Campos",
        pos: "LD",
        number: 25,
    },
    {
        id: 14,
        name: "Filipe Silva",
        pos: "LE",
        number: 70,
    },
    {
        id: 15,
        name: "Martim Brito",
        pos: "GR",
        number: 13,
    },
    {
        id: 16,
        name: "Miguel VirgÃ­lio",
        pos: "C",
        number: 9,
    },
    {
        id: 17,
        name: "Orlando Quenduca",
        pos: "GR",
        number: 21,
    },
    {
        id: 18,
        name: "Rafael Ferreira",
        pos: "PE",
        number: 15,
    },
    {
        id: 19,
        name: "TomÃ¡s Ferreira",
        pos: "PD",
        number: 17,
    },
    {
        id: 20,
        name: "Mauro Rodrigues",
        pos: "PE",
        number: 19,
    },
];

